language: python

os: linux
dist: xenial

python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install -U pip setuptools
  - pip install .
  - pip install -r requirements.txt
  - pip install python-coveralls

# start the Flask server for our tests
before_script:
  - python -m tests.test_server &

script:
  - py.test --ignore=tests/functional/test_functional.py --ignore=tests/test_server.py --cov requests_ntlm --cov-report term-missing tests

after_success:
  - coveralls

